config/routes.rb
Rails.application.routes.draw do

  get 'quick_view/home'
  get 'quick_view/view_terr'
  get 'quick_view/render_pdf'
  get 'quick_view/render_pdf_user'
  get 'quick_view/auto_checkin'
  post 'warning_messages/hide_message'
  get 'quick_view/no_longer_avail'
  get 'main/change_lang' => 'main#change_lang', :as=> 'main/change_lang'
  get 'map_layers/set_layer' => 'map_layers#set_layer', :as=>  'map_layers/set_layer'
  post 'clients/refresh_map' =>  'clients#refresh_map', :as=>  'clients/refresh_map'
  post 'addresses/refresh_map' =>  'addresses#refresh_map', :as=>  'addresses/refresh_map'
  get 'coordinates/new_zone' => 'coordinates#new_zone', :as=> 'coordinates/new_zone'
  get 'zones/clear_last_coordinate' => 'zones#clear_last_coordinate', :as=> 'zones/clear_last_coordinate'
  get 'zones/clear_coordinates' => 'zones#clear_coordinates', :as=> 'zones/clear_coordinates'
  get 'main/help' => 'main#help', :as=> 'main/help'
  get 'addresses/index_terr' => 'addresses#index_terr', :as=> 'addresses/index_terr'
  get 'addresses/home' => 'addresses#home', :as=> 'addresses/home'
  get 'addresses/new_from_street' => 'addresses#new_from_street', :as=> 'addresses/new_from_street'
  get 'addresses/export' => 'addresses#export', :as=> 'addresses/export'
  get 'addresses/what_territory' => 'addresses#what_territory', :as=> 'addresses/what_territory'
  get 'addresses/streetsearch' => 'addresses#streetsearch', :as=> 'addresses/streetsearch'
  get 'addresses/house_no_search' => 'addresses#house_no_search', :as=> 'addresses/house_no_search'
  get 'householders/home' => 'householders#home', :as=> 'householders/home'
  get 'householders/search' => 'householders#search', :as=> 'householders/search'
  get 'territories/home' => 'territories#home', :as=> 'territories/home'
  get 'addresses/index_street' => 'addresses#index_street', :as=> 'addresses/index_street'
  get 'territories/clear_last_coordinate' => 'territories#clear_last_coordinate', :as=> 'territories/clear_last_coordinate'
  get 'territories/clear_coordinates' => 'territories#clear_coordinates', :as=> 'territories/clear_coordinates'
  get 'territories/printedque' => 'territories#printedque', :as=> 'territories/printedque'
  get 'territories/select_new_type' => 'territories#select_new_type', :as=> 'territories/select_new_type'
  get 'territories/report' => 'territories#report', :as=> 'territories/report'
  get 'territories/index_zone' => 'territories#index_zone', :as=> 'territories/index_zone'
  get 'territories/view_all_ter_pins_with_phones' => 'territories#view_all_ter_pins_with_phones', :as=> 'territories/view_all_ter_pins_with_phones'
  get 'territories/check_in' => 'territories#check_in', :as=> 'territories/check_in'
  get 'territories/check_out' => 'territories#check_out', :as=> 'territories/check_out'
  get 'territories/view_all_ter_pins' => 'territories#view_all_ter_pins', :as=> 'territories/view_all_ter_pins'
  get 'territories/remove_from_que' => 'territories#remove_from_que', :as=> 'territories/remove_from_que'
  get 'territories/view_ter_householders_with_phones' => 'territories#view_ter_householders_with_phones', :as=> 'territories/view_ter_householders_with_phones'
  get 'territories/view_ter_householders_coords' => 'territories#view_ter_householders_coords', :as=> 'territories/view_ter_householders_coords'
  get 'territory_histories/report' => 'territory_histories#report', :as=> 'territory_histories/report'
  get 'upload/cleanup' => 'upload#cleanup', :as=> 'upload/cleanup'
  post 'territories/check_out_post' => 'territories#check_out_post', :as=> 'territories/check_out_post'
  post 'territories/check_out_new_user' => 'territories#check_out_new_user', :as=> 'territories/check_out_new_user'
  post 'addresses/what_territory_post' => 'addresses#what_territory_post', :as=> 'addresses/what_territory_post'
  post 'login/login' => 'login#login', :as=> 'login/login'
  get 'logout' => 'login#logout', :as=> :logout
  post 'upload/uploadFile' => 'upload#uploadFile', :as=> 'upload/uploadFile'
  resources :map_layers,  only: [:update, :create, :destroy, :index]
  resources :addresses
  resources :clients
  resources :coordinates
  resources :householders,  only: [:update, :create, :destroy, :index]
  resources :login
  resources :main
  resources :territories
  resources :territory_histories
  resources :upload
  resources :users
  resources :zones
  resources :territory_images

   root 'login#index'

end

app/models/territory_history.rb
class TerritoryHistory < ActiveRecord::Base
  belongs_to :territory
  belongs_to :user
end

app/controllers/territory_histories_controller.rb
class TerritoryHistoriesController < ApplicationController
    before_action :login_required
    before_action :is_any_admin_redirect
    before_action :set_territory_history, only: [:show, :edit, :update, :destroy]

  def index

     @territory_histories = TerritoryHistory.where(client_id: session[:client_id]).joins(:territory).paginate(:page => params[:page], :per_page => 30).order('territories.territory_no+0,territory_histories.check_out_date')
  end


  def show


  end


  def new
    @territory_history = TerritoryHistory.new
  end



  def edit

  end


  def create
    @territory_history = TerritoryHistory.new(territory_history_params)

    respond_to do |format|
      if @territory_history.save
        flash[:notice] = 'TerritoryHistory was successfully created.'
        format.html { redirect_to(@territory_history) }
       else
        format.html { render :action => "new" }
       end
    end
  end


  def update

    respond_to do |format|
      if @territory_history.update(territory_history_params)
        flash[:notice] = 'TerritoryHistory was successfully updated.'
        format.html { redirect_to(@territory_history) }
       else
        format.html { render :action => "edit" }
       end
    end
  end


  def destroy
    @territory_history = TerritoryHistory.find_by(id: params[:id],client_id: session[:client_id])
    @territory_history.destroy

    respond_to do |format|
      format.html { redirect_to(territory_histories_url) }
     end
  end




  def report

    @territories = Territory.where(client_id: session[:client_id]).includes(:territory_histories).paginate(:page => params[:page], :per_page => 30).order('territories.territory_no+0 ASC')

  end


    private
     def set_territory_history
      @territory_history = TerritoryHistory.find_by(id: params[:id],client_id: session[:client_id])
    end

  # Never trust parameters from the scary internet, only allow the white list through.
    def territory_history_params
      params.require(:territory_history).permit(:check_out_date, :check_in_date, :user_id, :territory_id, :client_id)
    end



end

app/views/territory_histories/edit.html.erb
<div class="card">
  <div class="card-header card-header-top">
    <h1><%=t :edit_history%></h1>
  </div>
  <div class="card-block">


<%= form_for(@territory_history) do |f| %>

<table class="table table-striped">
  <tr>
    <td>  <%=t :territory%> </td>
    <td> <%= f.text_field :territory_id %> </td>
  </tr>

  <tr>
    <td>  <%=t :check_out_date%> </td>
    <td>  <%= f.date_select :check_out_date,:use_month_numbers => true, :order => [:month,:day,:year]  %> </td>
  </tr>

  <tr>
    <td> <%=t :check_in_date %> </td>
    <td> <%= f.date_select :check_in_date,:include_blank => true,:use_month_numbers => true, :order => [:month,:day,:year] %> </td>
   </tr>

  <tr>
    <td> <%=t :user_id %> </td>
    <td>
      <%= f.select("country_id", User.where(client_id: current_user.client_id).order(:username).collect { |p| [p.username, p.id]}, {selected: @territory_history.user_id}, {class: 'text-field'}) %>
 </td>
  </tr>

  <tr>
    <td colspan="2"> <%= f.submit "#{t :update}", class: 'btn btn-primary' %> </td>
  </tr>
</table>

<% end %>

 </div>
</div>

app/views/territory_histories/index.html.erb
<div class="card">
  <div class="card-header card-header-top">
    <h1><%=t :territory_histories %></h1>
  </div>
  <div class="card-block">


<table class="table table-striped">
  <tr>
    <th><%=t :territory      %></th>
    <th><%=t :check_out_date %></th>
    <th ><%=t :check_in_date  %></th>
    <th><%=t :user_id %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @territory_histories.each do |territory_history| %>

  <tr>


    <td><%= territory_history.territory.territory_no %></td>
    <td><%= territory_history.check_out_date %></td>
    <td><%= territory_history.check_in_date %></td>
    <td><%= territory_history.user_id %></td>
    <td><%= link_to image_tag('view.png', size: '33x33'), territory_history %></td>
    <td><%= link_to image_tag('edit.png',size: '33x33'), edit_territory_history_path(territory_history) %></td>
    <td><%=link_to image_tag('trash.png',size: '33x33'), territory_history, :confirm => "#{t :are_you_sure}", :method => :delete %></td>
  </tr>
<% end %>
</table>
</div>

  <div class="digg_pagination">
    <%=will_paginate @territory_histories%>
  </div>

</div>

app/views/territory_histories/new.html.erb
<h1>New territory_history</h1>

<% form_for(@territory_history) do |f| %>


  <p>
    <b>Territory</b><br />
   <%=  f.select(:territory_id, Territory.find(:all,:conditions => "client_id = '#{session[:client_id]}'",:order=>"territory_no+0").collect {|c| [ c.territory_no, c.id ] }) %>

   <%= f.hidden_field(:client_id,:value => session[:client_id]) %>
  </p>
  <p>
    <%= f.label :check_out_date %><br />
    <%= f.date_select :check_out_date %>
  </p>
  <p>
    <%= f.label :check_in_date %><br />
    <%= f.date_select :check_in_date, :include_blank => true  %>
  </p>
  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', territory_histories_path %>

app/views/territory_histories/report.html.erb
<div class="card">
    <div class="card-header card-header-top">
        <h2><%=t :report_for%>
            <%=@territories[0].client.name%></h2>
    </div>

    <div class="card-block">

        <table class="table table-striped">

            <% for territory in @territories do%>

            <tr>
                <th><%=t :territory %></th>
                <th><%=t :user %>
                </th>
                <th><%=t :check_out_date %>
                </th>
                <th><%=t :check_in_date%>
                </th>
            </tr>
            <tr>

                <td><%= territory.territory_no %></td>

                <% territory.territory_histories.each do |t|%>

                <td>
                    <%= t.user.username %></td>

                <td>
                    <%= t.check_out_date %></td>

                <td class="out"><%= t.check_in_date %></td>
            </tr>
            <%end%>

            <% end %>

        </table>
    </div>
</div>

<div class="digg_pagination">
    <%=will_paginate @territories %>
</div>

</div>

app/views/territory_histories/show.html.erb
<div class="card">
  <div class="card-header card-header-top">
    <h1><%=t :territory_histories %></h1>
  </div>
  <div class="card-block">

    <table class="table table-striped">
      <tr>
        <td> <b><%=t :territory %> </b> </td>
        <td> <%= @territory_history.territory.territory_no %> </td>
      </tr>
      <tr>
        <td> <b><%=t :check_out_date %></b> </td>
        <td> <%= @territory_history.check_out_date %> </td>
      </tr>
      <tr>
        <td> <b><%=t :check_in_date %></b> </td>
        <td> <%= @territory_history.check_in_date %> </td>
      </tr>
      <tr>
        <td> <b><%=t :user_id%></b> </td>
        <td>  <%= @territory_history.user_id %></td>
        </tr>
        </table>

</div>
</div>