config/routes.rb
Rails.application.routes.draw do

  get 'quick_view/home'
  get 'quick_view/view_terr'
  get 'quick_view/render_pdf'
  get 'quick_view/render_pdf_user'
  get 'quick_view/auto_checkin'
  post 'warning_messages/hide_message'
  get 'quick_view/no_longer_avail'
  get 'main/change_lang' => 'main#change_lang', :as=> 'main/change_lang'
  get 'map_layers/set_layer' => 'map_layers#set_layer', :as=>  'map_layers/set_layer'
  post 'clients/refresh_map' =>  'clients#refresh_map', :as=>  'clients/refresh_map'
  post 'addresses/refresh_map' =>  'addresses#refresh_map', :as=>  'addresses/refresh_map'
  get 'coordinates/new_zone' => 'coordinates#new_zone', :as=> 'coordinates/new_zone'
  get 'zones/clear_last_coordinate' => 'zones#clear_last_coordinate', :as=> 'zones/clear_last_coordinate'
  get 'zones/clear_coordinates' => 'zones#clear_coordinates', :as=> 'zones/clear_coordinates'
  get 'main/help' => 'main#help', :as=> 'main/help'
  get 'addresses/index_terr' => 'addresses#index_terr', :as=> 'addresses/index_terr'
  get 'addresses/home' => 'addresses#home', :as=> 'addresses/home'
  get 'addresses/new_from_street' => 'addresses#new_from_street', :as=> 'addresses/new_from_street'
  get 'addresses/export' => 'addresses#export', :as=> 'addresses/export'
  get 'addresses/what_territory' => 'addresses#what_territory', :as=> 'addresses/what_territory'
  get 'addresses/streetsearch' => 'addresses#streetsearch', :as=> 'addresses/streetsearch'
  get 'addresses/house_no_search' => 'addresses#house_no_search', :as=> 'addresses/house_no_search'
  get 'householders/home' => 'householders#home', :as=> 'householders/home'
  get 'householders/search' => 'householders#search', :as=> 'householders/search'
  get 'territories/home' => 'territories#home', :as=> 'territories/home'
  get 'addresses/index_street' => 'addresses#index_street', :as=> 'addresses/index_street'
  get 'territories/clear_last_coordinate' => 'territories#clear_last_coordinate', :as=> 'territories/clear_last_coordinate'
  get 'territories/clear_coordinates' => 'territories#clear_coordinates', :as=> 'territories/clear_coordinates'
  get 'territories/printedque' => 'territories#printedque', :as=> 'territories/printedque'
  get 'territories/select_new_type' => 'territories#select_new_type', :as=> 'territories/select_new_type'
  get 'territories/report' => 'territories#report', :as=> 'territories/report'
  get 'territories/index_zone' => 'territories#index_zone', :as=> 'territories/index_zone'
  get 'territories/view_all_ter_pins_with_phones' => 'territories#view_all_ter_pins_with_phones', :as=> 'territories/view_all_ter_pins_with_phones'
  get 'territories/check_in' => 'territories#check_in', :as=> 'territories/check_in'
  get 'territories/check_out' => 'territories#check_out', :as=> 'territories/check_out'
  get 'territories/view_all_ter_pins' => 'territories#view_all_ter_pins', :as=> 'territories/view_all_ter_pins'
  get 'territories/remove_from_que' => 'territories#remove_from_que', :as=> 'territories/remove_from_que'
  get 'territories/view_ter_householders_with_phones' => 'territories#view_ter_householders_with_phones', :as=> 'territories/view_ter_householders_with_phones'
  get 'territories/view_ter_householders_coords' => 'territories#view_ter_householders_coords', :as=> 'territories/view_ter_householders_coords'
  get 'territory_histories/report' => 'territory_histories#report', :as=> 'territory_histories/report'
  get 'upload/cleanup' => 'upload#cleanup', :as=> 'upload/cleanup'
  post 'territories/check_out_post' => 'territories#check_out_post', :as=> 'territories/check_out_post'
  post 'territories/check_out_new_user' => 'territories#check_out_new_user', :as=> 'territories/check_out_new_user'
  post 'addresses/what_territory_post' => 'addresses#what_territory_post', :as=> 'addresses/what_territory_post'
  post 'login/login' => 'login#login', :as=> 'login/login'
  get 'logout' => 'login#logout', :as=> :logout
  post 'upload/uploadFile' => 'upload#uploadFile', :as=> 'upload/uploadFile'
  resources :map_layers,  only: [:update, :create, :destroy, :index]
  resources :addresses
  resources :clients
  resources :coordinates
  resources :householders,  only: [:update, :create, :destroy, :index]
  resources :login
  resources :main
  resources :territories
  resources :territory_histories
  resources :upload
  resources :users
  resources :zones
  resources :territory_images

   root 'login#index'

end

app/models/zone.rb
class Zone < ActiveRecord::Base

  before_destroy :ensure_no_children
  has_many :territories
  belongs_to :map_layer
  has_many :coordinates, dependent: :destroy
  belongs_to :client

  validates_presence_of :center_coordinate
  validates_presence_of :client_id
  validates_presence_of :zone_no
  before_create :check_map_layer



  def check_map_layer
    if self.map_layer_id.blank?
       self.map_layer_id = 1
    end
  end

  def self.no_cords(client_id)

  @zones_without = Array.new
  Zone.where(client_id: client_id).each do |z|
   if z.coordinates.count < 1
    @zones_without.push(z.id)
   end
  end

 return  @zones_without

  end




  def get_recipient_count
   @count = 0
   self.territories.each do |t|
      t.addresses.each do |a|
       @count += a.users.count
      end
   end

   @count

  end

 def get_address_count
  @count = 0
  self.territories.each do |t|

   @count += t.addresses.count

  end

  @count

 end


   def ensure_no_children

     if self.territories.count > 0
       return FALSE
     end

   end


end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController

   before_action :set_zone, only: [:clear_coordinates, :clear_last_coordinate, :edit, :destroy, :update, :show]
   before_action :check_client, only: [:edit, :show, :update, :destroy]
   before_action :setup

  def index


    @zones = Zone.where(client_id: current_user.client_id)

    respond_to do |format|
      format.html # index.html.erb
     end
  end






  def show

  end


  def new
    @zone = Zone.new

  end


  def edit

  end


  def clear_coordinates

    @Coordinates = Coordinate.where(zone_id: @zone.id)

    @Coordinates.each do |coord|
       coord.delete
    end

    redirect_to :controller=>"coordinates",:action => "new_zone",:zone_id=> @zone.id

  end

  def clear_last_coordinate

    @Coordinates = Coordinate.where(zone_id: @zone.id).order("id ASC")
    @Count = @Coordinates.count -1
    @Coordinates.last.delete

    redirect_to :controller=>"coordinates",:action => "new_zone",:zone_id=> @zone.id

  end


  def create
    @zone = Zone.new(zone_params)

    
    respond_to do |format|
      if @zone.save
        @msg = "#{t :zone}" + "#{t :record_created}"
        flash[:zone_notice] = @msg
        format.html { redirect_to(@zone) }
       else
         @errors = @zone.errors.full_messages
         flash[:zone_notice] = @errors
        format.html { render :action => "new" }
       end
    end
  end


  def update

    respond_to do |format|
      if @zone.update(zone_params)
        @msg = "#{t :zone}" + "#{t :record_updated}"
        flash[:zone_notice] = @msg
        format.html { redirect_to(@zone) }
       else
        format.html { render :action => "edit" }
       end
    end
  end


  def destroy
      respond_to do |format|
        if @zone.destroy
      format.html { redirect_to(zones_url) }
         else
           @msg = "#{t :zone}" + "#{t :record_deleted}"
           flash[:zone_notice] = @msg
         format.html { redirect_to(:back) }
        end
    end
  end

   private
  # Use callbacks to share common setup or constraints between actions.
   def set_zone
     @zone = Zone.find_by(id: params[:id], client_id: current_user.client_id)
   end

   def check_client
     is_same_client_redirect(@zone)
   end

  # Never trust parameters from the scary internet, only allow the white list through.
   def zone_params
     params.require(:zone).permit(:zone_no, :city, :state, :country_id, :description, :client_id, :center_coordinate, :zoom, :fill_color, :border_size,:border_color, :map_layer_id)
   end






end

app/views/zones/_form.html.erb
<% if @zone.errors.any? %>

<% @zone.errors.full_messages.each do |message| %>
<div class="alert alert-danger" role="alert">
    <%= message %>
</div>
<% end %>

<% end %>
<%= form_for(@zone) do |f| %>
<%= f.hidden_field(:client_id,value:  current_user.client_id) %>
<%= f.hidden_field :center_coordinate , class: 'text-field-wide' %></td>

<table class='table table-striped'>

<tr>
    <td colspan="2">

        <%=render 'map', zone: @zone, edit: 1 %>

    </td>
</tr>
<tr>
    <td>
        <b>
            <%=f.label :zone_no%>#
        </b>city
    <td><%= f.text_field :zone_no ,class: 'text-field-wide' %>
    </td>
</tr>

<tr>
    <td>
        <b><%=f.label :description %>
        </b>
    </td>
    <td>
        <%= f.text_area :description, class: 'text-area-wide' %>
    </td>
</tr>

<tr>
    <td>
        <b><%=f.label :city %>
        </b>
    </td>
    <td>
        <%= f.text_field :city, value: current_user.client.city,class: 'text-field-wide' %></td>
</tr>
<tr>
    <td>
        <b><%=f.label :state %>
        </b>
    </td>
    <td><%= f.text_field :state, value: current_user.client.state, class: 'text-field-wide' %></td>
</tr>

<tr>
    <td>
        <b>
            <%=f.label :zoom%>
        </b>
    </td>
    <td>
        <%= f.select(:zoom,([['1','12'], ['2','13'],['3','14'],['4','15'],['5','16'],['6','17'],['7','18'],['8','19']]),{}, {class: 'text-field-wide' } )%>
    </td>
</tr>

<%if @zone.new_record? %>
<%@def_border = '#F30000' %>
<%else%>
<%@def_border =  @zone.border_color %>
<%end%>

<tr>
    <td>
        <b>
            <%=f.label :fill_color%>
        </b>
    </td>
    <td>
        <%= f.check_box :fill_color %>
    </td>
</tr>
<tr>
    <td>
        <b>
            <%=f.label :border_color%>
        </b>
    </td>
    <td><%= f.color_field :border_color,  value: @def_border %>
    </td>
</tr>
<tr>
    <td>
        <b>
            <%= f.label :border_size %>
        </b>
    </td>
    <td><%= f.select :border_size, { "1" => "1","5" => "5","10" => "10","15" => "15","20" => "20"},{},{class: 'text-field-wide'} %>
    </td>
</tr>

<tr>
    <td colspan="2">
        <% new_or_update(@zone) %>
        <%= f.submit "#{@button_txt}", class: 'btn btn-primary' %>
    </td>
</tr>

<% end %>
</table>

app/views/zones/_map.html.erb
<style>
    body { margin:0; padding:0; }
    #map_c<%=zone.id%> { margin-bottom:30px;position:relative;top:10px; height:500px; bottom:0; width:100%; }
</style>

<style>
    .css-icon {
        width: 0;
        height: 0;

    }
</style>

<% get_map_layer ## returns @map_layer %>
<%= render 'map_layers/set_layer_zone', zone_id: zone.id %>

<div id='map_c<%=zone.id%>'></div>

<%if zone.new_record?%>
<%@coord = get_best_coord(current_user.client) %>
<%@zoom = 12 %>

<%else%>
<%@coord = zone.center_coordinate %>
<%@zoom = zone.zoom %>
<%end%>



<script>

    <%if edit == 1 %>
     var position = document.getElementById('zone_center_coordinate');
    <%end%>

    L.mapbox.accessToken = 'pk.eyJ1IjoibWNyb3dkZXIiLCJhIjoiY2lqcTcyd2YwMDFrb3Rya285MjMxdXQydSJ9.hIHusY9FJsXj9RBUNWC4pA';


        var map_c<%=zone.id%> = L.map('map_c<%=zone.id%>').setView([<%=@coord%>],"<%=@zoom%>");
        L.tileLayer('<%=@map_layer.layer_url%>', {
            attribution: 'EcuaERP',
            maxZoom: '<%=@map_layer.max_zoom%>'

            <%if !@map_layer.min_zoom.blank?%>
                , min_zoom: '<%= @map_layer.min_zoom %>'
             <%end%>

            <%if !@map_layer.map_type.blank?%>
            , type:  '<%=@map_layer.map_type%>'
            <%end%>

            <%if !@map_layer.file_ext.blank?%>
           , ext: '<%= @map_layer.file_ext %>'
            <%end%>

            <%if !@map_layer.subdomains.blank?%>
           , subdomains: '<%=@map_layer.subdomains %>'
            <%end%>

        }).addTo(map_c<%=zone.id%>);


      var cssIcon = L.divIcon({
        // Specify a class name we can refer to in CSS.
        className: 'css-icon',
        html: '<img src=/assets/pin.png>',
        iconSize: [60, 60]
    });

    var marker = L.marker(new L.LatLng(<%=@coord%>), {
        icon: cssIcon
      <%if edit == 1 %>,
        draggable: true
      <%end%>
    });


    marker.on('dragend', ondragend);
    marker.bindPopup('<%=t :map_drag_marker %>');
    marker.addTo(map_c<%=zone.id%>);




   var line_points = [
      <% zone.coordinates.each do |c| %>
        [<%=c.coordinate%>],
      <%end%>
    ];




    var polyline_options = {

        color: '<%=zone.border_color%>'
        <%if zone.fill_color? %>,
        fill: true
        <%end%>
        <%if !zone.border_size.blank?%>,
        weight: <%=zone.border_size%>
        <%end%>

    };

    var polyline = L.polyline(line_points, polyline_options).addTo(map_c<%=zone.id%>);

    <%if edit == 1%>
    function ondragend() {
        var m = marker.getLatLng();
        position.value = m.lat + ',' + m.lng;
    }
    <%end%>
</script>

app/views/zones/edit.html.erb
    <div class="card">
        <div class="card-header card-header-top">
            <table class="table table-noborder table-nopadding">
                <tr>
                    <td class="card-title no-border">
                        <h2>
                            <%=t :edit_zone%>
                        </h2>

                    </td>
                    <td class="buttons">
                        <%=link_to "", {controller: 'zones', action: 'index'}, class: 'tdtn btn-primary btn-home btn-top' %>
                    </td>
                </tr>
            </table>
        </div>
        <div class="card-block">
          <%= render 'form' %>
        </div>
    </div>

app/views/zones/index.html.erb
<div class="card">
    <div class="card-header card-header-top">
        <table class="table table-noborder table-nopadding">
            <tr>
                <td class="card-title no-border">
                  <br />
                    <h2>
                        <%= t :zones %>
                    </h2>
                </td>
                <td>
                  <%= link_to raw("<icon class='fa fa-5x fa-plus-circle'></icon>"), new_zone_path, class: 'btn btn-primary btn-top' %>
                </td>
            </tr>
        </table>
    </div>
    <div class="card-block">


        <%@zones.each do |zone| %>

        <table class="table table-striped">
            <tr>

                <th><%=t :zone%></th>
                <th style='width:50%;'><%=t :descriptiontion%></th>
                <th><%=t :view%></th>
                <th><%=t :edit%>
                </th>
                <th><%=t :delete%>
                </th>
                <th><%=t :terrs_in_zone%>
                </th>
            </tr>
            <tr>
                <td class="zone"><%=h zone.zone_no %></td>
                <td class="descriptiontion"><%=h zone.description %></td>
                <td><%= link_to image_tag("view.png",:class=>"button",:size=>"26x26",:title=>"#{t :view}"), zone %></td>
                <td><%= link_to image_tag("edit.png",:class=>"button",:size=>"26x26",:title=>"#{t :edit}"), edit_zone_path(zone) %></td>
                <td><%= link_to image_tag("delete.png",:class=>"button",:size=>"26x26",:title=>"#{t :delete}"), zone, :confirm => "#{t :are_you_sure}", :method => :delete %></td>
                <td><%= link_to image_tag("samplestaticmap.png",:class=>"button",:size=>"50x26",:title=>"#{t :terrs_in_zone}"),:controller=>"territories",:action=>"index_zone", :zone_id=>zone.id %></td>
            </tr>
            <tr>
                <td colspan="6">
                    <%= render 'map', zone: zone, edit: 0 %>
                </td>
            </tr>
        </table>
        <% end %>

        <br/>

    </div>
</div>

app/views/zones/new.html.erb
<div class="card">
    <div class="card-header card-header-top">
        <table class="table table-noborder table-nopadding">
            <tr>
                <td class="card-title no-border">
                    <br/>
                    <h2>
                        <%=t :zone_new%>
                    </h2>
                </td>
                <td class="buttons">
                    <%=link_to "", {controller: 'zones', action: 'index'}, class: 'tdtn btn-primary btn-home btn-top' %>
                </td>
            </tr>
        </table>
    </div>
    <div class="card-block">
        <%=render 'form' %>
    </div>


    <%if show_msg('zone_cord')%>
     <%= render 'layouts/warn_map', msg: "#{t :warn_map_zone}", msg_name: 'zone_cord' %>
    <%end%>

app/views/zones/show.html.erb
<div class="card">
    <div class="card-header card-header-top">
        <table class="table table-noborder table-nopadding">
            <tr>
                <td class="card-title no-border">
                    <h2>
                        <%= t :zones %>
                    </h2>
                </td>
                <td class="buttons">
                    <%= link_to raw("<icon class='fa fa-5x fa-home'></icon>"),zones_path, class: 'btn btn-primary btn-top2' %>

                    <%= link_to  raw("<icon class='fa fa-5x fa-edit'></icon>"),  edit_zone_path(@zone), class: 'btn btn-primary btn-top2' %>
                </td>
            </tr>
        </table>
    </div>
    <div class="card-block">

        <%if flash[:zone_notice]%>
        <div class="alert alert-success" role="alert">
            <%= flash[:zone_notice] %>
        </div>
        <%end%>

        <table class="table table-striped">
            <tr>
                <td>
                    <b><%=t :zone%>#
                        <%= @zone.zone_no %>
                    </b>
                </td>
                <td class='button'></td>
            </tr>
            <tr>
                <td>
                    <b><%=t :descriptiontion%></b>
                </td>
                <td><%= @zone.description %></td>
            </tr>

            <tr>
                <td colspan="2" data-no-turbolink='true'>
                    <%= link_to "#{t :coordinates}", {controller: 'coordinates', action: 'new_zone', zone_id: @zone.id}, class: 'left btn btn-primary',  data: { no_turbolink: true }%>

                  <%if @zone.coordinates.count < 2%>
                    <%=image_tag('arrow.png', class: 'arrow' )%>
                    <%=t :create_coords_help %>
                  <%end%>

                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <%= render 'map', zone: @zone, edit: 0 %>
                </td>
            </tr>
        </table>

    </div>
</div>