config/routes.rb
Rails.application.routes.draw do

  get 'quick_view/home'
  get 'quick_view/view_terr'
  get 'quick_view/render_pdf'
  get 'quick_view/render_pdf_user'
  get 'quick_view/auto_checkin'
  post 'warning_messages/hide_message'
  get 'quick_view/no_longer_avail'
  get 'main/change_lang' => 'main#change_lang', :as=> 'main/change_lang'
  get 'map_layers/set_layer' => 'map_layers#set_layer', :as=>  'map_layers/set_layer'
  post 'clients/refresh_map' =>  'clients#refresh_map', :as=>  'clients/refresh_map'
  post 'addresses/refresh_map' =>  'addresses#refresh_map', :as=>  'addresses/refresh_map'
  get 'coordinates/new_zone' => 'coordinates#new_zone', :as=> 'coordinates/new_zone'
  get 'zones/clear_last_coordinate' => 'zones#clear_last_coordinate', :as=> 'zones/clear_last_coordinate'
  get 'zones/clear_coordinates' => 'zones#clear_coordinates', :as=> 'zones/clear_coordinates'
  get 'main/help' => 'main#help', :as=> 'main/help'
  get 'addresses/index_terr' => 'addresses#index_terr', :as=> 'addresses/index_terr'
  get 'addresses/home' => 'addresses#home', :as=> 'addresses/home'
  get 'addresses/new_from_street' => 'addresses#new_from_street', :as=> 'addresses/new_from_street'
  get 'addresses/export' => 'addresses#export', :as=> 'addresses/export'
  get 'addresses/what_territory' => 'addresses#what_territory', :as=> 'addresses/what_territory'
  get 'addresses/streetsearch' => 'addresses#streetsearch', :as=> 'addresses/streetsearch'
  get 'addresses/house_no_search' => 'addresses#house_no_search', :as=> 'addresses/house_no_search'
  get 'householders/home' => 'householders#home', :as=> 'householders/home'
  get 'householders/search' => 'householders#search', :as=> 'householders/search'
  get 'territories/home' => 'territories#home', :as=> 'territories/home'
  get 'addresses/index_street' => 'addresses#index_street', :as=> 'addresses/index_street'
  get 'territories/clear_last_coordinate' => 'territories#clear_last_coordinate', :as=> 'territories/clear_last_coordinate'
  get 'territories/clear_coordinates' => 'territories#clear_coordinates', :as=> 'territories/clear_coordinates'
  get 'territories/printedque' => 'territories#printedque', :as=> 'territories/printedque'
  get 'territories/select_new_type' => 'territories#select_new_type', :as=> 'territories/select_new_type'
  get 'territories/report' => 'territories#report', :as=> 'territories/report'
  get 'territories/index_zone' => 'territories#index_zone', :as=> 'territories/index_zone'
  get 'territories/view_all_ter_pins_with_phones' => 'territories#view_all_ter_pins_with_phones', :as=> 'territories/view_all_ter_pins_with_phones'
  get 'territories/check_in' => 'territories#check_in', :as=> 'territories/check_in'
  get 'territories/check_out' => 'territories#check_out', :as=> 'territories/check_out'
  get 'territories/view_all_ter_pins' => 'territories#view_all_ter_pins', :as=> 'territories/view_all_ter_pins'
  get 'territories/remove_from_que' => 'territories#remove_from_que', :as=> 'territories/remove_from_que'
  get 'territories/view_ter_householders_with_phones' => 'territories#view_ter_householders_with_phones', :as=> 'territories/view_ter_householders_with_phones'
  get 'territories/view_ter_householders_coords' => 'territories#view_ter_householders_coords', :as=> 'territories/view_ter_householders_coords'
  get 'territory_histories/report' => 'territory_histories#report', :as=> 'territory_histories/report'
  get 'upload/cleanup' => 'upload#cleanup', :as=> 'upload/cleanup'
  post 'territories/check_out_post' => 'territories#check_out_post', :as=> 'territories/check_out_post'
  post 'territories/check_out_new_user' => 'territories#check_out_new_user', :as=> 'territories/check_out_new_user'
  post 'addresses/what_territory_post' => 'addresses#what_territory_post', :as=> 'addresses/what_territory_post'
  post 'login/login' => 'login#login', :as=> 'login/login'
  get 'logout' => 'login#logout', :as=> :logout
  post 'upload/uploadFile' => 'upload#uploadFile', :as=> 'upload/uploadFile'
  resources :map_layers,  only: [:update, :create, :destroy, :index]
  resources :addresses
  resources :clients
  resources :coordinates
  resources :householders,  only: [:update, :create, :destroy, :index]
  resources :login
  resources :main
  resources :territories
  resources :territory_histories
  resources :upload
  resources :users
  resources :zones
  resources :territory_images

   root 'login#index'

end

app/models/territory.rb
class Territory < ActiveRecord::Base

  belongs_to :user
  belongs_to  :zone
  has_many :addresses
  has_many :coordinates, :dependent => :delete_all
  has_many :territory_histories
  belongs_to :client
  before_update :create_key
  has_many :territory_images
  before_destroy :ensure_no_children
  validates_presence_of :zone_id
  validates_presence_of :center_coordinate
  validates_presence_of :user_id, if: Proc.new { |r| !r.is_checked_in? }
  before_create :check_map_layer


  def check_map_layer
    if self.map_layer_id.blank?
       self.map_layer_id = 1
    end
  end


 def create_key

  @checked = self.is_checked_in_was
  @now_checked = self.is_checked_in

  if @checked && !@now_checked
    self.view_key = Territory.encrypt(self.user_id.to_s+self.checkout_date.to_s)
  end


 end







 def self.encrypt(key)
   @encrypted  = Digest::MD5.hexdigest(key);
   return @encrypted
 end


  def self.no_cords(client_id)

  @territories_without = Array.new
  Territory.where(client_id: client_id).each do |t|
   if t.coordinates.count < 1
    @territories_without.push(t.id)
   end
  end

   return  @territories_without

  end

  def get_user_id

   @user = User.find_by(id: self.user_id)
   if @user.nil?
     ""
   else
     "#{@user.full_name}"
   end


  end


  def ensure_no_children
     unless self.addresses.count < 1
       self.errors.add_to_base "Can't destroy a Territory having addresses"
       raise ActiveRecord::Rollback

     end
   end











end

app/controllers/territories_controller.rb
class TerritoriesController < ApplicationController
   before_filter :login_required
   before_filter :set_territory, only: [:check_in,:check_out_new_user, :check_out, :check_out_post,:clear_last_coordinate, :clear_coordinates, :show, :edit, :update, :destroy,:view_all_ter_pins,:view_ter_householders]
   before_filter :is_any_admin_redirect, only: [:check_in,:check_out_new_user, :check_out, :check_out_post,:clear_last_coordinate, :clear_coordinates, :edit, :update, :destroy]
   before_action :setup


  def index
    is_any_admin_redirect
    @territories= Territory.where(client_id: session[:client_id]).paginate(:page => params[:page], :per_page => 30).order("territory_no+0") # Return only Requested street
    respond_to do |format|
      format.html # index.html.erb
     end
  end


    def index_zone
      is_any_admin_redirect
      @zone_id = params[:zone_id]
      @territories= Territory.where(client_id: session[:client_id], zone_id: @zone_id).paginate(:page => params[:page], :per_page => 30).order("territory_no+0") # Return only Requested street

      respond_to do |format|
        format.html # index.html.erb
      end

    end




  def show

     is_same_client_redirect(@territory)

     if current_user.can_manage_hh? && !current_user.isadmin? && @territory.user_id.to_s != current_user.id.to_s
      redirect_to controller: 'main', action: 'no_perms'
     end

     @bordercount = 0


  end


  def new
    @zone = Zone.find(params[:zone_id])
    @territory = Territory.new
    respond_to do |format|
      format.html # new.html.erb
    end
  end



  def edit

  end



  def create
    @territory = Territory.new(territory_params)

    respond_to do |format|
      if @territory.save


        flash[:tnotice] = 'Territory was successfully created.'
        format.html { redirect_to(@territory) }


      else
        @zone = @territory.zone
        format.html { render :action => "new"}
      end
    end
  end





  def update

    respond_to do |format|
      if @territory.update(territory_params)
        flash[:tnotice] = 'Territory was successfully updated.'
        format.html { redirect_to(@territory) }
      else
        format.html { render :action => "edit" }
      end
    end
  end


  def destroy
    @territory = Territory.find_by(id: params[:id],client_id: session[:client_id])

    respond_to do |format|
     if @territory.destroy
      format.html { redirect_to(territories_url) }
     else
      flash[:dnotice] = 'Territory can not be deleted while it has addresses.'
      format.html { redirect_to(:back) }

     end
    end
  end


  def view_all_ter_pins
    #a printout of this is what is given to publishers to take out in service.
    @addresses = Address.where(territory_id: @territory.id, client_id: session[:client_id]).paginate(:page => params[:page], :per_page => 30).order("street,house_no")
  end



   def check_out
    @user = User.new

    if flash['co_notice']
    else
     session[:referrer] = request.referrer
    end

   end


    def check_out_new_user

      @user = User.new
      @user.username = params[:username]
      @user.fname = params[:fname]
      @user.lname = params[:lname]
      @user.email = params[:email]
      @user.must_change_pass = TRUE
      @user.can_manage_hh = params[:can_manage_hh]
      @user.is_client_admin = FALSE
      @user.client_id = current_user.client_id
      @user.password = params[:username]


      respond_to do |format|
        if @user.save

          @territory.user_id = @user.id
          @territory.is_checked_in = false
          @D = Date.today
          @territory.checkout_date = @D

          if !params[:check_back_in2].blank?
           @t = Chronic.parse(params[:check_back_in2].to_s, :guess => true)
           @territory.check_back_in = @t.to_date
          end

          if @territory.save

            if !@territory.user.isadmin && !@territory.user.can_manage_hh
             UserMailer.send_terr(@user,@territory).deliver_now
            end

            if @territory.user.isadmin || @territory.user.can_manage_hh
             UserMailer.send_user(@user,@user.username).deliver_now
            end

          end

          @History = TerritoryHistory.new
          @History.territory_id = @territory.id
          @History.check_out_date =   @D
          @History.client_id = session[:client_id]
          @History.user_id = @user_id
          @History.save

          format.html { redirect_to  session[:referrer] }
        else
          @errors = @user.errors
          format.html { render :check_out }
        end
      end

    end



    def check_out_post
      require 'chronic'

      if !params[:cob].blank?
      flash[:tnotice] = "#{t :checked_out_success}"
      @user_id = params[:cob]
      @user = User.find_by(id: @user_id)
      @territory.user_id = @user_id
      @territory.is_checked_in = false
      @D = Date.today
      @territory.checkout_date = @D

      if !params[:check_back_in].blank?
       @t = Chronic.parse(params[:check_back_in].to_s, :guess => true)
       @territory.check_back_in = @t.to_date
      end

      if @territory.save

        if !@territory.user.isadmin && !@territory.user.can_manage_hh
         UserMailer.send_terr(@user,@territory).deliver_now
        end

      end

      @History = TerritoryHistory.new
      @History.territory_id = @territory.id
      @History.check_out_date =   @D
      @History.client_id = session[:client_id]
      @History.user_id = @user_id
      @History.save
      redirect_to session[:referrer]

    else

      flash['co_notice'] = "#{t :must_select_user}"
      redirect_to action: 'check_out', id: @territory.id

      end


    end


    def check_in

      flash[:tnotice] = "#{t :checked_in_success}"

      check_in_terr(@territory)

      redirect_to :controller =>"territories", action: 'show', id: @territory.id


    end




    def home


    end




    def report
      @territories = Territory.where(client_id: session[:client_id]).order("territory_no+0")

    end



    def notfound

    end




def clear_coordinates

  @Coordinates = Coordinate.where(territory_id: @territory.id)

  @Coordinates.each do |coord|
     coord.delete
  end

  redirect_to :controller=>"coordinates",:action => "new",:territory_id=> @territory.id

end

def clear_last_coordinate

  @Coordinates = Coordinate.where(territory_id: @territory.id).order("id ASC")
  @Count = @Coordinates.count -1

  @Coordinates.last.delete unless @Coordinates.count < 1


  redirect_to :controller=>"coordinates",:action => "new",:territory_id=> @territory.id

end

   private
  # Use callbacks to share common setup or constraints between actions.
   def set_territory
     @territory = Territory.find_by(id: params[:id], client_id: session[:client_id])
   end

  # Never trust parameters from the scary internet, only allow the white list through.
   def territory_params
     params.require(:territory).permit(:check_back_in, :view_key, :center_coordinate,:zoom, :fill_color, :border_color,:map_layer_id, :territory_no, :descrip,:notes, :image, :zone_id, :last_worked, :border_size, :checkin_date, :checkout_date, :user_id, :is_checked_in, :client_id)
   end


end

app/views/territories/_new_from_zone.html.erb
<% @zones = Zone.where(client_id: current_user.client_id) %>
<%= select_tag "zone", options_from_collection_for_select(@zones, "id", "zone_no"), include_blank: true, style: 'font-size:10px;color:black;width:100%;', prompt: "#{t :territory_new_in_zone}" %>


<script>
    $(function () {
        // bind change event to select
        $('#zone').bind('change', function () {
            var url = $(this).val();
            if (url) {


                window.location = "/territories/new?zone_id=" + url; // redirect

            }
            return false;
        });
    });
</script>




<script>
    $("#zone").select2({
        theme: "bootstrap"
    });

</script>

app/views/territories/check_out.erb
<div class="card">
    <div class="card-header-top card-header">
        <table class="table table-noborder table-nopadding">
            <tr>
                <td class="card-title no-border">
                    <h2>
                        <%= t :check_out %>
                    </h2>
                </td>
                <td class="buttons">
                    <%= link_to raw("<icon class='fa fa-5x fa-home'></icon>"),territories_path, class: 'btn btn-primary btn-top' %>
                </td>
            </tr>
        </table>
    </div>

    <div class="card-block">

  <%if flash['co_notice'] %>
     <p class='notice'>
       <%= flash['co_notice'] %>
     </p>
  <%end%>

        <br>
        <ul class="nav nav-tabs"  id='ch' role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#checkout" role="tab"><%=t :check_out %></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#checkout_new" role="tab"><%=t :check_out%>
                    -
                    <%=t :newuser %></a>
            </li>

        </ul>

        <div class="tab-content">
            <div class="tab-pane active" id="checkout" role="tabpanel">
                <br>
                <%= form_tag '/territories/check_out_post' do -%>
                <table class="table table-striped">
                    <tr>
                        <td><%=t :user_id %></td>
                        <td>
                            <%= select_tag "cob", options_from_collection_for_select(User.where(client_id: current_user.client_id).order('fname ASC'), "id", "full_name"), class: 'text-field-wide', prompt: "#{t :select_user}"  %>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <%=t :check_back_in %>
                        </td>
                        <td>
                            <%=  text_field_tag 'check_back_in', nil, {class: 'datepicker text-field-wide'} %></td>
                    </td>
                </tr>
                <%= hidden_field_tag "id", @territory.id %>
                <tr>
                    <td colspan="2"><%= submit_tag "#{t :check_out}", :class => 'btn btn-primary'%></td>
                </tr>
            </table>
            <% end -%>

        </div>
        <div class="tab-pane" id="checkout_new" role="tabpanel">

            <br>


            <%if @user.errors.any? %>
            <% @user.errors.full_messages.each do |message| %>
            <div class="alert alert-danger" role="alert">
                <%= message %>
            </div>
            <% end %>
            <script>
              $(function () {
                $('#ch a:last').tab('show')
              })
            </script>
            <%end%>

            <%= form_tag '/territories/check_out_new_user' do -%>
            <table class="table table-striped">
                <tr>
                    <td>
                        <%=t :username%>
                    </td>
                    <td>
                        <%=text_field_tag "username", nil, {class: 'text-field-wide'} %>
                    </td>
                </tr>
                <tr>
                    <td>
                        <%=t :first_name%>
                    </td>
                    <td>
                        <%=text_field_tag "fname", nil, {class: 'text-field-wide'} %>
                    </td>
                </tr>
                <tr>
                    <td>
                        <%=t :last_name%>
                    </td>
                    <td>
                        <%=text_field_tag "lname", nil, {class: 'text-field-wide'} %>
                    </td>
                </tr>
                <tr>
                    <td>
                        <%=t :email%>
                    </td>
                    <td>
                        <%=text_field_tag "email", nil, {class: 'text-field-wide'} %>
                    </td>
                </tr>
                <tr>
                    <td>
                        <%=t :is_admin %>
                    </td>
                    <td>
                      <%= check_box_tag :is_client_admin %>
                      <icon class='fa fa-3x fa-question-circle' style='float:right' title='<%=t :is_client_admin_help %>'>
                      </icon>
                    </td>
                </tr>
                 <script>
                 $('#is_client_admin').click(function(){
                     if (this.checked) {
                         $('#can_manage_hh').prop('checked', false).uniform();
                     }
                 })
                 </script>
                <tr>
                    <td>
                        <%=t :can_manage_hh %>
                    </td>
                    <td>
                      <%= check_box_tag :can_manage_hh  %>
                      <icon class='fa fa-3x fa-question-circle' style='float:right' title='<%=t :can_manage_hh_help %>'>
                      </icon>
                    </td>
                </tr>
                <script>
                $('#can_manage_hh').click(function(){
                    if (this.checked) {
                        $('#is_client_admin').prop('checked', false).uniform();
                    }
                })
                </script>
                <tr>
                    <td>
                        <%=t :check_back_in %>
                    </td>
                    <td>
                        <%=  text_field_tag 'check_back_in2',nil, {class: 'datepicker text-field-wide'} %></td>
                </td>
            </tr>
            <%= hidden_field_tag "id", @territory.id %>
            <tr>
                <td colspan="2"><%= submit_tag "#{t :check_out}", :class => 'btn btn-primary'%></td>
            </tr>
        </table>

        <% end -%>

    </div>

</div>

</div>
</div>

<script type="text/javascript" language="javascript">
$(document).ready(function () {
    $('.datepicker').datepicker({language: "<%=current_user.sitelang%>"});
});
</script>

</div>

app/views/territories/edit.html.erb
<div class="card">
  <div class="card-header card-header-top">
    <table class="table table-noborder table-nopadding">
      <tr>
        <td class="card-title no-border">
          <h2> <%= t :territory %> </h2>
          <% if flash[:notice] %>
              <p class='notice' id="notice"><%= notice %></p>
          <% end %>
        </td>
        <td class="buttons">
           <%= link_to "", territories_path, class: 'btn btn-primary btn-home btn-top' %>
        </td>
      </tr>
    </table>
  </div>
  <div class="card-block">

    <%= render 'form', territory: @territory, zone: @territory.zone %>


  </div>
</div>

app/views/territories/index.html.erb
<div class="card">
    <div class="card-header card-header-top">
        <table class="table table-noborder table-nopadding">
            <tr>
                <td class="card-title">
                    <h2>
                        <%=t :territories %>
                    </h2>
                </td>

                <td class='buttons'>
                    <%= link_to raw("<icon class='fa fa-5x fa-home'></icon>"), territories_home_path, class: 'btn btn-primary btn-top' %>
                </td>
            </tr>
        </table>
    </div>

    <div class="card-block">
        <%  @territories.each do |territory| %>
        <table class="table table-striped table-bordered">
            <tr>
                <th><%=t :territory_number %></th>
                <% if current_user.client.is_language_based? %>
                <th></th>
                <%end%>
                <th><%=t :territory_status %></th>
                <th><%=t :description %></th>
                <%if territory.is_checked_in? %>
                <th><%= t :last_worked  %></th>
                <%end%>
                <th><%= t :zone  %></th>
                <th><%=t :show%></th>
                <th><%=t :edit%></th>
                <th><%=t :delete%></th>

            </tr>
            <tr>
                <td><%= territory.territory_no  %></td>
                <% if current_user.client.is_language_based? %>
                <td>
                    <%if !territory.is_checked_in? && !territory.user_id.nil? %>
                    <%= link_to image_tag("pdf.jpeg",:size=>"25x25",:class=>"button",:title=>"#{t :print_addresses}"),controller: 'quick_view', action: "render_pdf_user",:id =>territory.id %>
                    <%end%>

                    <%= link_to raw("<icon style='margin-left:8px;' class='fa fa-2x fa-address-card'></icon>"),{controller: 'addresses', action: "index_terr",:territory_id =>territory.id},:title=>"#{t :print_addresses}" %>
                    <%= link_to image_tag("map.png",:size=>"25x25",:class=>"button"),:action=>"view_all_ter_pins",:id =>territory.id %>
                </td>
                <%end%>

                <td>
                    <%if territory.is_checked_in? %>
                    <%= link_to "#{t :check_out}",{controller: 'territories' ,:action=>"check_out",:id =>territory.id}, class: 'btn btn-primary', :confirm => "#{t :check_in_sure}"%>
                    <%else%>
                    <%= link_to "#{t :check_in}- #{territory.user.username}", {controller: 'territories' ,:action=>"check_in",:id =>territory.id}, class: 'btn btn-primary'%>
                    <%end%>
                </td>
                <td><%=h territory.description %></td>

                <%if territory.is_checked_in? %>
                <td><%=h territory.last_worked %></td>
                <%end%>
                <td>

                    <%=link_to("#{territory.zone.zone_no}",:controller=>"zones",:action=> 'show',id: territory.zone.id)%>

                </td>
                <td><%= link_to image_tag("view.png",:class=>"button",:size=>"26x26",:title=>"#{t :view}"), territory %></td>
                <td><%= link_to image_tag("edit.png",:class=>"button",:size=>"26x26",:title=>"#{t :edit}"), edit_territory_path(territory) %></td>
                <td><%= link_to image_tag("delete.png",:class=>"button",:size=>"26x26",:title=>"#{t :delete}"), territory, :confirm => "#{t :are_you_sure}", :method => :delete %></td>
            </tr>
        </table>

        <div class="territory_img">
            <%=render 'map', territory: territory, edit: 0, zone: territory.zone %>
        </div>

        <br>

        <% end %>
        <div class="paginate">
            <%=  will_paginate @territories,:next_label=>"#{t :next}",:previous_label=>"#{t :previous}"  %>
        </div>

    </div>

</div>

app/views/territories/notfound.html.erb
<%= image_tag "logo.jpg" %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<CENTER>
<%=t :terrnotfound%>
</CENTER>

app/views/territories/report.html.erb
<div class="card">
  <div class="card-header card-header-top">
    <table class="table table-noborder table-nopadding">
        <tr>
            <td class="card-title no-border">
                <h2 >
                    <%= t :territories %>
                </h2>
            </td>
            <td class="buttons">
                <%= link_to raw("<icon class='fa fa-5x fa-home'></icon>"), territories_home_path, class: 'btn btn-primary btn-home btn-top' %>
             </td>
        </tr>
    </table>
  </div>
  <div class="card-block">



  <table class="table table">
    <tr>
    <th>#</th>
    <th><%="#{t :territory_status}"%></th>
    <th><%= "#{t :user_id}"  %></th>
    <th><%=t :descriptiontion %> </th>
    <th><%= "#{t :checked_out}"  %></th>
    <th><%= "#{t :last_worked}" %></th>
    <th><%= t :zone  %> </th>
    <th><%= t :address_count  %> </th>
    </tr>


<% for territory in @territories %>

    <tr>
      <td><%= link_to territory.territory_no, {:controller => 'territories',:action=> 'show',:id =>territory.id},{:style=>'color:black;', :class => "nolink"} %></b></td>
      <td>
        <%if territory.is_checked_in == true %>
         <h5 class="ci"> <%=t :checked_in%> </h5>
        <%end%>

        <%if territory.is_checked_in == false     %>
          <% @checkout_date = territory.checkout_date %>
          <% @today = Date.today %>
          <% @length = @today - @checkout_date %>

           <%if @length > 89 %>
            <h4><%=t :overdue %></h4>
           <%else%>
           <h5 class="co"> <%=t :checked_out  %> </h5>
           <%end%>
        <%end%>
    </td>

    <td>

     <%if territory.is_checked_in == false %>
       <%=territory.user.username%>
     <%end%>

    </td>

    <td><%=h territory.description %></td>
    <td><%=h territory.checkout_date %></td>
    <td><%=h territory.last_worked %></td>
    <td><%=territory.zone.zone_no %>   </td>
    <td><%=territory.addresses.count %>   </td>
    </tr>
<% end %>


</table>
</div>
</div>

app/views/territories/view_all_ter_householders.html.erb
<div class="card">

    <style>
        body {
            margin: 0;
            padding: 0;
        }
        #map_c {
            margin-bottom: 30px;
            position: relative;
            top: 10px;
            height: 500px;
            bottom: 0;
            width: 100%;
        }

        .css-icon {
            width: 0;
            height: 0;
        }

    </style>

    <div class="card-header-top card-header-top">
        <table class="table table-noborder table-nopadding">
            <tr>
                <td class="card-title">
                    <h2>
                        <%=t :territory %>
                    </h2>
                </td>
                <td class='button'>
                  <%= link_to "", territories_path, class: 'right btn btn-primary btn-home btn-top' %>
                </td>
            </tr>
        </table>
    </div>

    <div class="card-block">

        <% get_map_layer ## returns @map_layer %>
        <%= render 'map_layers/set_layer_terr',territory_id: @territory.id %>
         <br>
         <br>
        <div id='map_c'></div>

        <script>

            L.mapbox.accessToken = 'pk.eyJ1IjoibWNyb3dkZXIiLCJhIjoiY2lqcTcyd2YwMDFrb3Rya285MjMxdXQydSJ9.hIHusY9FJsXj9RBUNWC4pA';

            <%  @cord = @territory.center_coordinate %>

            var map_c = L.map('map_c').setView([<%=@cord%>], "<%=@territory.zoom%>");

            L.tileLayer('<%=@map_layer.layer_url%>', {
                attribution: 'EcuaERP',
                maxZoom: '<%=@map_layer.max_zoom%>',

                <%if !@map_layer.min_zoom.blank?%>,
                min_zoom: '<%= @map_layer.min_zoom %>' <%end%>

                <%if !@map_layer.map_type.blank?%>,
                type: '<%=@map_layer.map_type%>' <%end%>

                <%if !@map_layer.file_ext.blank?%>,
                ext: '<%= @map_layer.file_ext %>' <%end%>

                <%if !@map_layer.subdomains.blank?%>,
                subdomains: '<%=@map_layer.subdomains %>' <%end%>

            }).addTo(map_c);

            <% @territory.addresses.each do |a| %>

            var cssIcon<%=a.id%> = L.divIcon({
                // Specify a class name we can refer to in CSS.
                className: 'css-icon',
                html: '<img src=/assets/pin.png>',
                iconSize: [60, 60]
            });

            var marker<%=a.id%> = L.marker(new L.LatLng(<%=a.coordinate%>), {icon: cssIcon<%=a.id%>});

            marker<%=a.id%>.on('dragend', ondragend);
            marker<%=a.id%>.bindPopup('<%=t :address%> : <%=a.house_no%> <%=a.street%><br><%if a.users.any?%><%=a.users[0].full_name%><%end%>');
            marker<%=a.id%>.addTo(map_c);
            <%end%>


            var line_points2 = [<%@territory.coordinates.each do |t| %>
            [<%=t.coordinate%>],
            <%end%>
            ];

            <%if @territory.border_color.blank?%>
            <%@color = 'red'%>
            <%else%>
            <%@color = @territory.border_color %>
            <%end%>

            var polyline_options2 = {
                color: '<%=@color%>'

                 <%if @territory.fill_color? %>,
                  fill: true
                 <%end%>

                <%if !@territory.border_size.blank?%>,
                  weight: <%=@territory.border_size%>
                <%end%>
            };
            var polyline2 = L.polyline(line_points2, polyline_options2).addTo(map_c);



        </script>

    </div>
</div>